[project]
name = "airbnb_price_prediction"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.29.5",
    "jupyter>=1.1.1",
    "numpy>=2.2.1",
    "pandas>=2.2.3",
]

[tool.setuptools]
packages = ["src"]
